using TankMuseum.Core.Exhibits;
using TankMuseum.Core.News;

namespace TankMuseum.Core;

public interface IDataStorage
{
    public ValueTask<IEnumerable<NewsItem>> GetNewsItemsAsync();
    public ValueTask<IEnumerable<Exhibit>> GetExhibitsAsync();
    public ValueTask AddExhibitAsync(Exhibit exhibit);
    public ValueTask RemoveExhibitAsync(Exhibit exhibit);
}

public sealed class DataStorage : IDataStorage
{
    public ValueTask<IEnumerable<NewsItem>> GetNewsItemsAsync() => ValueTask.FromResult(_newsItems.AsEnumerable());
    public ValueTask<IEnumerable<Exhibit>> GetExhibitsAsync() => ValueTask.FromResult(_exhibits.AsEnumerable());

    public ValueTask AddExhibitAsync(Exhibit exhibit)
    {
        _exhibits.Add(exhibit);

        return ValueTask.CompletedTask;
    }

    public ValueTask RemoveExhibitAsync(Exhibit exhibit)
    {
        _exhibits.Remove(exhibit);

        return ValueTask.CompletedTask;
    }

    #region sample data

    // Sample data generated by AI, no guarantee of accuracy
    // Image sources and rights belong to their respective owners - don't use on public sites!

    private readonly List<Exhibit> _exhibits =
    [
        new()
        {
            Id = 1,
            Name = "M4 Sherman",
            Description
                = "The M4 Sherman was the primary tank used by the United States during World War II, known for its reliability and versatility.",
            ServiceStartYear = 1942,
            ServiceEndYear = 1957,
            AddedToMuseumCollectionAt = new LocalDate(1972, 5, 12),
            UnitsProduced = 49234,
            Country = "United States",
            Armor = "Up to 75 mm",
            Armament = "75 mm M3 L/40 gun",
            Crew = 5,
            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/0/0e/Sherman_Dresden_1.jpg"
        },
        new()
        {
            Id = 2,
            Name = "Sherman Firefly",
            Description
                = "A British variant of the American M4 Sherman, the Firefly was equipped with a powerful 17-pounder anti-tank gun.",
            ServiceStartYear = 1944,
            ServiceEndYear = 1958,
            AddedToMuseumCollectionAt = new LocalDate(1975, 3, 15),
            UnitsProduced = 2100,
            Country = "United Kingdom",
            Armor = "Up to 76 mm",
            Armament = "QF 17-pounder (76.2 mm) gun",
            Crew = 4,
            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/e/e8/Sherman_firefly_bovington_2014.JPG"
        },
        new()
        {
            Id = 3,
            Name = "Mark IV Tank",
            Description
                = "An evolution of the earlier British tanks, the Mark IV saw extensive use during World War I.",
            ServiceStartYear = 1917,
            ServiceEndYear = 1918,
            AddedToMuseumCollectionAt = new LocalDate(1980, 9, 10),
            UnitsProduced = 1220,
            Country = "United Kingdom",
            Armor = "Up to 12 mm",
            Armament = "Two 6-pounder guns and three machine guns",
            Crew = 8,
            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/b/bd/Mark_IV.jpg"
        },
        new()
        {
            Id = 4,
            Name = "Chieftain",
            Description
                = "The Chieftain was a main battle tank of the British Army during the Cold War, featuring advanced armor and weaponry.",
            ServiceStartYear = 1966,
            ServiceEndYear = 1995,
            AddedToMuseumCollectionAt = new LocalDate(2000, 7, 20),
            UnitsProduced = 2265,
            Country = "United Kingdom",
            Armor = "Up to 195 mm",
            Armament = "120 mm L11A5 rifled gun",
            Crew = 4,
            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/ad/Chieftain_Tank_%289628802829%29.jpg"
        },
        new()
        {
            Id = 5,
            Name = "Panzerkampfwagen III (Panzer III)",
            Description = "A German medium tank used extensively in World War II, designed to engage enemy armor.",
            ServiceStartYear = 1939,
            ServiceEndYear = 1945,
            AddedToMuseumCollectionAt = new LocalDate(1985, 11, 5),
            UnitsProduced = 5774,
            Country = "Germany",
            Armor = "Up to 70 mm",
            Armament = "50 mm KwK 39 L/60 gun",
            Crew = 5,
            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/17/PzKpfwIIIH_Saumur_noBG_01.jpg"
        },
        new()
        {
            Id = 6,
            Name = "T-34",
            Description
                = "The T-34 was a Soviet medium tank that had a profound impact on the field of tank design, combining firepower, mobility, and protection.",
            ServiceStartYear = 1940,
            ServiceEndYear = 1958,
            AddedToMuseumCollectionAt = new LocalDate(1978, 6, 30),
            UnitsProduced = 84070,
            Country = "Soviet Union",
            Armor = "Up to 60 mm",
            Armament = "76.2 mm F-34 gun (later upgraded to 85 mm)",
            Crew = 4,
            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Tank_T-34.JPG/1200px-Tank_T-34.JPG"
        },
        new()
        {
            Id = 7,
            Name = "Leopard 2",
            Description
                = "A German main battle tank renowned for its advanced technology and superior performance in mobility and firepower.",
            ServiceStartYear = 1979,
            ServiceEndYear = null,
            AddedToMuseumCollectionAt = new LocalDate(2015, 8, 12),
            UnitsProduced = 3500,
            Country = "Germany",
            Armor = "Composite armor",
            Armament = "120 mm Rheinmetall L/44 smoothbore gun",
            Crew = 4,
            ImageUrl
                = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Leopard_2_A5_der_Bundeswehr.jpg/1200px-Leopard_2_A5_der_Bundeswehr.jpg"
        },
        new()
        {
            Id = 8,
            Name = "M1 Abrams",
            Description
                = "The main battle tank of the United States Army, known for its powerful armament and advanced armor.",
            ServiceStartYear = 1980,
            ServiceEndYear = null,
            AddedToMuseumCollectionAt = new LocalDate(2018, 4, 18),
            UnitsProduced = 10000,
            Country = "United States",
            Armor = "Composite Chobham armor",
            Armament = "120 mm M256 smoothbore gun",
            Crew = 4,
            ImageUrl
                = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/M1A1_Abrams_Tank_in_Camp_Fallujah_retouched.jpg/1200px-M1A1_Abrams_Tank_in_Camp_Fallujah_retouched.jpg"
        },
        new()
        {
            Id = 9,
            Name = "T-54/T-55",
            Description
                = "A series of Soviet main battle tanks introduced after World War II, widely used during the Cold War.",
            ServiceStartYear = 1947,
            ServiceEndYear = null,
            AddedToMuseumCollectionAt = new LocalDate(1992, 10, 25),
            UnitsProduced = 86000,
            Country = "Soviet Union",
            Armor = "Up to 200 mm with add-on armor",
            Armament = "100 mm D-10T cannon",
            Crew = 4,
            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/86/T-54-.jpg"
        },
        new()
        {
            Id = 10,
            Name = "Challenger 2",
            Description
                = "The current main battle tank of the British Army, featuring enhanced armor and a powerful 120 mm rifled gun.",
            ServiceStartYear = 1998,
            ServiceEndYear = null,
            AddedToMuseumCollectionAt = new LocalDate(2020, 3, 5),
            UnitsProduced = 447,
            Country = "United Kingdom",
            Armor = "Dorchester Level 2 Chobham armor",
            Armament = "120 mm L30A1 rifled gun",
            Crew = 4,
            ImageUrl
                = "https://upload.wikimedia.org/wikipedia/commons/3/30/Challenger_2_Main_Battle_Tank_patrolling_outside_Basra%2C_Iraq_MOD_45148325.jpg"
        },
        new()
        {
            Id = 11,
            Name = "Centurion",
            Description
                = "One of the most successful post-war tank designs, the Centurion served in numerous conflicts around the world.",
            ServiceStartYear = 1946,
            ServiceEndYear = null,
            AddedToMuseumCollectionAt = new LocalDate(1989, 12, 1),
            UnitsProduced = 4423,
            Country = "United Kingdom",
            Armor = "Up to 152 mm",
            Armament = "105 mm L7A1 rifled gun",
            Crew = 4,
            ImageUrl = "https://tankmuseum.org/wp-content/uploads/2020/04/Centurion-feat-1100x500.jpg"
        },
        new()
        {
            Id = 12,
            Name = "Tiger I",
            Description
                = "A German heavy tank of World War II, the Tiger I was famous for its powerful 88 mm gun and thick armor.",
            ServiceStartYear = 1942,
            ServiceEndYear = 1945,
            AddedToMuseumCollectionAt = new LocalDate(1976, 9, 23),
            UnitsProduced = 1347,
            Country = "Germany",
            Armor = "Up to 120 mm",
            Armament = "88 mm KwK 36 L/56 gun",
            Crew = 5,
            ImageUrl = "https://tankmuseum.org/wp-content/uploads/2020/04/Tiger-I-feat-1100x500.jpg"
        }
    ];

    private readonly List<NewsItem> _newsItems =
    [
        new(1000,
            Instant.FromUtc(2004, 2, 15, 10, 0),
            "Introducing the Mark IV Tank Exhibit",
            "We are delighted to unveil the latest addition to our museum—the World War I Mark IV tank. This historic vehicle showcases the evolution of armored warfare and is now available for viewing.",
            [3]),
        new(1001,
            Instant.FromUtc(2005, 6, 10, 14, 30),
            "Annual Summer Family Day Announced",
            "Bring your family to our annual Summer Family Day! Enjoy interactive exhibits, tank demonstrations, and educational workshops suitable for all ages.",
            []),
        new(1002,
            Instant.FromUtc(2006, 12, 5, 9, 0),
            "New Archive Display: Letters from the Front",
            "Explore personal letters from tank crew members during World War II in our new archive display. Gain insight into their experiences and the history of tank warfare.",
            [1, 5, 6]),
        new(1003,
            Instant.FromUtc(2007, 3, 20, 11, 15),
            "Panzer III Arrives at the Museum",
            "We are excited to announce the arrival of the Panzer III tank. This German medium tank played a crucial role during World War II and adds depth to our collection.",
            [5]),
        new(1004,
            Instant.FromUtc(2008, 8, 25, 15, 45),
            "Live Tank Demonstrations This Weekend",
            "Join us this weekend for live tank demonstrations! Witness historic tanks in action and learn about their mechanics and history from our experts.",
            [1, 6]),
        new(1005,
            Instant.FromUtc(2009, 12, 20, 16, 0),
            "Holiday Greetings from the Tank Museum",
            "Season's greetings to all our visitors and supporters. We appreciate your enthusiasm and look forward to welcoming you in the New Year.",
            []),
        new(1006,
            Instant.FromUtc(2010, 4, 18, 10, 30),
            "Exclusive Lecture: The Evolution of Tank Design",
            "Attend an exclusive lecture on the evolution of tank design by renowned historian Dr. Jane Smith. Discover how tanks have transformed over the decades.",
            [8]),
        new(1007,
            Instant.FromUtc(2011, 7, 22, 13, 0),
            "Children's Educational Program Launched",
            "We are pleased to launch our new educational program for children, featuring interactive exhibits and activities designed to inspire young minds.",
            []),
        new(1008,
            Instant.FromUtc(2012, 11, 5, 9, 15),
            "Restoration Complete: The Sherman Firefly",
            "After months of meticulous work, the restoration of the Sherman Firefly tank is complete. Come see this iconic vehicle restored to its former glory.",
            [1, 2]),
        new(1009,
            Instant.FromUtc(2013, 2, 28, 11, 0),
            "Tank Museum Wins Heritage Award",
            "We are honored to receive the National Heritage Award for our contributions to preserving military history. Thank you to all who support our mission.",
            []),
        new(1010,
            Instant.FromUtc(2014, 6, 14, 14, 30),
            "New Exhibit: The Challenger 2 Main Battle Tank",
            "Discover the technology behind the British Army's Challenger 2 Main Battle Tank in our newest exhibit, showcasing modern advancements in armored warfare.",
            [10]),
        new(1011,
            Instant.FromUtc(2015, 9, 10, 10, 0),
            "Museum Expansion Completed",
            "We are excited to announce the completion of our museum expansion, featuring additional exhibit space and improved visitor facilities.",
            []),
        new(1012,
            Instant.FromUtc(2016, 12, 1, 12, 45),
            "Winter Military Vehicle Parade",
            "Join us for a spectacular parade of historic military vehicles this winter. Experience the sights and sounds of these incredible machines in motion.",
            []),
        new(1013,
            Instant.FromUtc(2017, 3, 17, 16, 15),
            "Interactive Tank Simulator Now Open",
            "Experience the thrill of commanding a tiger tank with our new interactive simulator. Perfect for visitors who want a hands-on experience of tank operations.",
            [12]),
        new(1014,
            Instant.FromUtc(2018, 5, 29, 9, 30),
            "Special Exhibit: Tanks of the Cold War",
            "Explore our special exhibit on Cold War-era tanks, highlighting the technological advancements and strategic roles these vehicles played.",
            [4, 7, 9]),
        new(1015,
            Instant.FromUtc(2019, 8, 12, 13, 0),
            "Volunteer Opportunities at the Museum",
            "We are seeking enthusiastic volunteers to join our team. Opportunities are available in various departments. Apply now to be part of our mission.",
            []),
        new(1016,
            Instant.FromUtc(2020, 11, 7, 10, 15),
            "Online Virtual Tour Now Available",
            "Experience the Tank Museum from the comfort of your home with our new virtual tour of the Centurion. Explore exhibits and learn about tank history online.",
            [11]),
        new(1017,
            Instant.FromUtc(2021, 2, 14, 11, 30),
            "Valentine's Day Special: Love and War",
            "Join us for a special Valentine's Day event exploring stories of love and companionship among tank crews during wartime.",
            []),
        new(1018,
            Instant.FromUtc(2022, 5, 1, 15, 0),
            "Celebrating International Workers' Day",
            "We honor the workers behind the production of tanks and military vehicles. Learn about their contributions in our special exhibit.",
            []),
        new(1019,
            Instant.FromUtc(2023, 9, 9, 9, 0),
            "Tankfest 2023 Tickets Now on Sale",
            "Don't miss Tankfest 2023, the world's best display of historic moving armor. Get your tickets now for an unforgettable experience.",
            []),
        new(1020,
            Instant.FromUtc(2024, 12, 25, 12, 0),
            "Merry Christmas from the Tank Museum",
            "Wishing all our visitors and supporters a very Merry Christmas and a Happy New Year. Thank you for being part of our journey.",
            []),
        new(1021,
            Instant.FromUtc(2025, 1, 1, 10, 0),
            "New Year, New Exhibits Coming Soon",
            "We have exciting new exhibits planned for this year. Stay tuned for updates on what's coming to the Tank Museum in 2025.",
            []),
        new(1022,
            Instant.FromUtc(2025, 3, 15, 11, 0),
            "Special Exhibition: Women in Armored Warfare",
            "Discover the stories of women who have contributed to tank design, production, and operations in our latest special exhibition.",
            []),
        new(1023,
            Instant.FromUtc(2025, 6, 30, 14, 0),
            "Summer Tank Camp for Teens",
            "Enroll your teenagers in our Summer Tank Camp, where they can learn about military history, engineering, and teamwork through engaging activities.",
            []),
        new(1024,
            Instant.FromUtc(2025, 9, 5, 9, 0),
            "Commemorating the Centenary of Tank Development",
            "Join us as we commemorate 100 years of tank development with special events, exhibits, and guest speakers throughout the month.",
            [])
    ];

    #endregion
}
